[package]
name = "hydration-reminder"
version = "1.0.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
image = "0.25.9"

[profile.opt]
inherits = "release"
lto = true
codegen-units = 1
strip = true
panic = "abort"
